{# Copyright (c) Pelagicore AB 2016 #}
{% import "qface/qtcpp.j2" as cpp %}
{{ cpp.autogenerated()}}
{% set module_name = '{0}Module'.format(module.module_name|upper_first) %}
{% set major = module.majorVersion %}
{% set minor = module.minorVersion %}
#include "plugin.h"

#include <qqml.h>

#include "generated/{{module|identifier}}_gen.h"

{% for interface in module.interfaces %}
#include "{{interface|lower}}.h"
{% endfor %}

void Plugin::registerTypes(const char *uri)
{
    // @uri {{module}}
{% for interface in module.interfaces %}
    qmlRegisterType<{{interface}}>(uri, {{major}}, {{minor}}, "{{interface}}");
{% endfor %}

{% for struct in module.structs %}
    qRegisterMetaType<{{struct}}>();
    qmlRegisterUncreatableType<{{struct}}Factory>(uri, {{major}}, {{minor}}, "{{struct}}Factory", "Factory can not be created");
{% endfor %}

}
